### ISSUE TITLE
pretrain weight for dla in Graph-VoI

### ISSUE THREAD

**Issue by iMbaGong** [Nightmare-n/GD-MAE#10]
hi, thank for share your great work.
i notice that in `dla.py`:
```
def dla34(pretrained=True, **kwargs):  # DLA-34
    model = DLA([1, 1, 1, 2, 2, 1],
                [16, 32, 64, 128, 256, 512],
                block=BasicBlock, **kwargs)
    return model
```
i can`t find any code to load the pretrain weight.
how can i get and load the pretrain weight for dla?

**Comment by Nightmare-n** [comment]
The model would automatically load the [pretrained weight of dla](https://drive.google.com/file/d/173eCABB3Hw261q50v5maTP4zOQJ0qfTd/view) via [this line](https://github.com/Nightmare-n/GD-MAE/blob/abd05ce2c2c0a5d02736e3fb0ad6ddbea0bb2bba/tools/train.py#L130) according to the name of sub-modules.
