### ISSUE TITLE
velodyne_reduced

### ISSUE THREAD

**Issue by Karkers** [Nightmare-n/GD-MAE#11]
how can i get this dataset

**Comment by Nightmare-n** [comment]
Hi, you could refer to [this](https://github.com/Nightmare-n/GD-MAE/blob/abd05ce2c2c0a5d02736e3fb0ad6ddbea0bb2bba/pcdet/datasets/kitti/kitti_dataset.py#L381) and [this](https://github.com/open-mmlab/mmdetection3d/blob/47e56e1dafc1024de5c773549c14b9a408dd9198/tools/dataset_converters/kitti_converter.py#L307) to create the reduced point clouds. Or, you could directly change the filename `velodyne_reduced` of [this line](https://github.com/Nightmare-n/GD-MAE/blob/abd05ce2c2c0a5d02736e3fb0ad6ddbea0bb2bba/pcdet/datasets/kitti/kitti_dataset.py#L64) to  `velodyne`, which would not affect the results when the flag of `FOV_POINTS_ONLY` is set to True.
