### ISSUE TITLE
Support voxel-based GD-MAE?

### ISSUE THREAD

**Issue by synsin0** [Nightmare-n/GD-MAE#13]
Thanks for your great work. In the code I see only the pillar implementation(assert height dimension is 1 in spt_backbone.py). I wonder whether you may support voxel-based implementation. Does GD-MAE support voxel-based embedding? Why and why not?

**Comment by Nightmare-n** [comment]
The MAE-style pretraining could also be used for voxel-based embedding (as far as I know, there is not much difference between voxel-based and pillar-based models). Since the baseline are pillar-based models (e.g., SPT), we only do experiments for them.
