### ISSUE TITLE
关于Graph-VoI 的测试结果

### ISSUE THREAD

**Issue by yingyang-1** [Nightmare-n/GD-MAE#23]
首先，非常感谢您优秀的工作！

您在论文中展示的Graph-VoI 的测试结果为：91.89（easy） 83.27（mod.） 77.78（hard）。但我使用您提供的预训练模型生成txt文件提交到test sever上得到的结果分别是：91.12，82.18，75.29，是怎么回事呀？是我生成txt文件的方式不对吗？不是修改kitti_dataset中test后面的val为test嘛？另外，我想请教一下如何得到FPS的呢？非常感谢！！！
![图片22](https://github.com/Nightmare-n/GD-MAE/assets/118244443/12b38b3f-83f2-409a-be8a-d545783d8ade)

**Comment by Nightmare-n** [comment]
1. We use train+val for training when submitting to the test server. 2. The running time or fps (evaluated by 1 GPU) is available [here](https://github.com/Nightmare-n/GD-MAE/blob/abd05ce2c2c0a5d02736e3fb0ad6ddbea0bb2bba/tools/eval_utils/eval_utils.py#L89).
