### ISSUE TITLE
about separately and end-to-end

### ISSUE THREAD

**Issue by phoebedddd** [Nightmare-n/GD-MAE#3]
What's the difference between the two training?

![image](https://user-images.githubusercontent.com/34564111/230888728-bef29425-2379-4508-a9bf-10f8bb8fa033.png)

**Comment by Nightmare-n** [comment]
separately: when training a two-stage model, the weights of the first stage are frozen, so we need to train a single-stage model first, and then a two-stage model.
end-to-end: we can directly train the two-stage model end-to-end (comment out the `FREEZE_LAYERS` in config files).

**Comment by phoebedddd** [comment]
> separately: when training a two-stage model, the weights of the first stage are frozen, so we need to train a single-stage model first, and then a two-stage model. end-to-end: we can directly train the two-stage model end-to-end (comment out the `FREEZE_LAYERS` in config files).

Ok, I see. Thank you very much! Best wishes for you!
