### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)

### ISSUE THREAD

**Issue by phoebedddd** [Nightmare-n/GD-MAE#4]
File "../pcdet/datasets/augmentor/database_sampler.py", line 26, in __init__
    **self.sampler_cfg.BACKEND.KWARGS
AttributeError: 'EasyDict' object has no attribute 'KWARGS'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 40282) of binary: /usr/local/bin/python

Hello,How to solve this error? I only use one GPU.Looking forward to your reply!Best wishes!

**Comment by Nightmare-n** [comment]
Thank you for pointing out this issue. This bug has been fixed.

**Comment by Pe0p1e024** [comment]
How to solve this error? I also saw that！How to fix it？Looking forward to your reply!

**Comment by phoebedddd** [comment]
> How to solve this error? I also saw that！How to fix it？Looking forward to your reply!
Using four Gpus seems to solve this problem.
